### PR TITLE
fix for vs2013 compile

### PR DESCRIPTION
**Pull request by guanlisheng**
better to use std::atomic_init

### CODE REVIEW

**Comment by JMLX42** [comment]
does it fix #30 ?

**Comment by Tomasu** [comment]
I actually had to revert this. Somehow I missed properly testing it, and std::atomic_init wasn't compiling properly in GCC at all. It will have to be done in a different way.

**Comment by JMLX42** [comment]
Does it mean it is supposed to compile on VS2013?

**Comment by Tomasu** [comment]
Theoretically it should just work as is on VS2013. assuming it implements `std::atomic<>` types properly.

**Pull request merged**
